build: &build
  steps:
    - checkout
    - run:
        name: "Initialize opam"
        command: |
          opam init --auto-setup
          opam remote add ocamlorg https://opam.ocaml.org -p 0 || true
          opam remote remove default || true
    - run:
        name: "Build changeset"
        command: |
          opam pin add changeset . -y
    - run:
        name: "Run test"
        command: |
          opam config exec jbuilder runtest

version: 2
jobs:
  4.06.0:
    docker:
      - image: ocaml/opam:debian-9_ocaml-4.06.0
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.06.0"
    <<: *build

workflows:
  version: 2
  build-deploy:
    jobs:
      - 4.06.0
